services:
  - type: web
    name: ai-chemistry-chatbot
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromGroup: render
      # AI APIキー（デプロイ後に設定）
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      # Supabase設定（デプロイ後に設定）
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      # Stripe設定（デプロイ後に設定）
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PRICE_BASIC_MONTHLY
        sync: false
      - key: STRIPE_PRICE_PRO_MONTHLY
        sync: false 